import { useEffect, useState } from "react";
import photo from "../../../assets/PedroCosta.jpeg";
import classes from "./About.module.css";
import Loading from "../../others/Loading/Loading";

/**
 * About Component
 *
 * This component fetches and displays information about me.
 * It uses the useState and useEffect hooks from React, and CSS modules for styling.
 *
 * The component maintains three state variables: 'about', 'loading', and 'error'.
 * 'about' is an array of strings representing paragraphs of information about me.
 * 'loading' is a boolean indicating whether the data is currently being fetched.
 * 'error' is a boolean indicating whether an error occurred while fetching the data.
 *
 * The component includes a useEffect hook that fetches the data from 'data/about.json' when the component mounts.
 * If the fetch is successful, 'about' is set to the 'about' property of the data, and 'loading' is set to false.
 * If the fetch fails, 'error' is set to true, and 'loading' is set to false.
 *
 * The component conditionally renders different content based on the state.
 * If 'error' is true, it renders a message indicating that the data could not be loaded.
 * If 'loading' is true, it renders a loading spinner.
 * Otherwise, it renders a div with an image and text about me.
 * The text is generated by mapping over the 'about' array and creating a paragraph for each string.
 *
 */
const About = () => {
  const [about, setAbout] = useState([] as string[]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch("data/about.json")
      .then((response) => response.json())
      .then((data) => {
        setAbout(data.about);
        setLoading(false);
      })
      .catch((error) => {
        setError(true);
        setLoading(false);
      });
  }, []);

  if (error) {
    return (
      <>
        <h4 className={classes.contentTitle}>About Me</h4>
        <p className={classes.justify}>
          Sorry, we couldn't load the information. Please, try again later.
        </p>
      </>
    );
  }

  if (loading) {
    return (
      <>
        <h4 className={classes.contentTitle}>About Me</h4>
        <Loading />
      </>
    );
  }

  return (
    <>
      <div className={classes.about}>
        <div className={classes.imageContainer}>
          <img className={classes.image} src={photo} alt="Pedro Costa" />
        </div>
        <div className={classes.textContainer}>
          <h4 className={classes.contentTitle}>About Me</h4>
          {about.map((paragraph, index) => (
            <p className={classes.justify} key={index}>
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </>
  );
};

export default About;
